version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
