version: 0.0
os: linux
files:
  - source: /
    destination: /
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/afterinstall
      timeout: 300
      runas: root
  